#+STARTUP: hidestars
#+AUTHOR: thingywhat
#+TITLE: Finding a formula to model a spanking.

I am in the process of developing a spanking simulation library. A
little library that can be used for either fun or other research. But
I am not overly happy with it -- I wish it were more accurate.

So, what do we want to do with this document? We want to find a
formula; A formula that I can use to accurate model a spanking!
Something I can plug into my simulation library; something that anyone
can use.

Now let the hunt begin!

* Components
Modelling a spanking requires tracking several individual components
of the spanking... Spanking "factors", if you will.

Below, we have a number of components we will need to keep track of
along with some Common Lisp implementations of functions we could use
to model the properties of each:

** Kinetic energy of each slap
The force of an individual swat will additively determine how much the
spankees butt hurts, as each swat's energy is transferred from the
spankers hand or implement to the spankees butt.

[[http://en.wikipedia.org/wiki/Kinetic_energy][Kinetic energy]] can be defined as:

\begin{equation}
E_k = 1/2 mv^2
\end{equation}

Where =E_k= is the kinetic energy in Joules (J), =m= is the mass of
the implement, and =v= is the velocity of said implement.

A function modelling this would be:
#+BEGIN_SRC lisp :tangle yes :exports code :padline no
  (defun kinetic-energy (mass velocity)
    "Returns the kinetic energy (In Joules) for a passed in mass (In Kg)
  and a passed in velocity. (In meters per second)"
    (* (* 0.5 mass) (expt velocity 2)))
#+END_SRC

#+RESULTS:
: KINETIC-ENERGY

The mass of each slap is equal to the amount of weight that it can
move, whereas the velocity is how fast the hand or implement is
moving.

I could not find any sources online that measure the average person's
slap, but there is a ton of information on punching and
chopping. Chopping seems equivalent enough, though more research will
need to go into this later.

According to [[https://arnulfo.wordpress.com/2007/07/24/physics-of-punching/][this blog]], a beginning karate student can chop at a speed
of about 20 feet per second. That is a completely wound up chop, but
gives a nice number to work with. It also measured the speed of a
black belt with a speed of 46 feet per second, with a 1 1/2 pound
hand, and a force of 2,800 newtons. We won't use that speed since the
air resistance of an open palm is more than it is for a chop, and most
spankers aren't black-belts in karate, so it would be unrealistic
except for as a hypothetical mind-game.

Also, according to [[https://drive.google.com/file/d/0BzqnGkfQdjftcllBdy0tVG80Ync/view?usp=sharing][this paper]] (Also [[file:./Strength.pdf][saved locally]] in case that goes
offline.), the downward press ranges for humans pushing at 120 degrees
down (To their lap, the direction force is used for OTK spanking after
impact) would be:

#+TBLNAME: downward-press-weight
| Weak (<5%) | Average (5%-95%) | Strong (>%95) | Standard Deviation |
|------------+------------------+---------------+--------------------|
|         24 |               60 |           124 |                 24 |

So!

First we need to do some unit conversion so we can do some simple
math:

*** Unit conversion
First lets convert the weight of a hand from pounds to Kg so we can
easily convert to Kg * m^2 / s^2 (Joules).
#+NAME: hand-mass
#+BEGIN_SRC lisp :exports both
  ;; 1 pound is about 0.45 Kg
  (* 1.5 0.45)
#+END_SRC

#+RESULTS: hand-mass
: 0.67499995

And meters per second is used rather than feet per second so, lets
convert 20 feet to meters.

#+NAME: beginner
#+BEGIN_SRC lisp :exports both
  ;; 1 foot is about 0.30 meters
  (* 20 0.3)
#+END_SRC

#+RESULTS: beginner
: 6.0

Also, since the force study was in pounds, lets convert that to a list
in Kgs:
#+NAME: press-mass
#+BEGIN_SRC lisp :exports both :var weight=downward-press-weight
  (mapcar (lambda (x) (* x 0.45)) (first weight))
#+END_SRC

#+RESULTS: press-mass
| 10.799999 | 27.0 | 55.8 | 10.799999 |

So, we have enough force to move 27Kg on average when someone is
pushing down to their lap, a weak spanker could push around 10Kg, and
a super-buff steroid-induced rump-destroyer could push 55.8
Kg. (Ouch!)

*** Hand spanking kinetic energy
Plugging the above figures into our function above give us:
#+NAME: hand-energy
#+BEGIN_SRC lisp :exports both :var mass=press-mass velocity=beginner
  (mapcar (lambda (mass) (kinetic-energy mass velocity)) (first mass))
#+END_SRC

#+RESULTS: hand-energy
| 194.4 | 486.0 | 1004.39996 | 194.4 |

Now that's one heck of a range, with the weakest spanker only capable
of smacking with just under 200 Joules of energy, and with the hardest
spanking with a force of over 1000 Joules.

Of course, our average spankers can spank with a reasonable ~500
Joules of force with a standard deviation of around 200 Joules.

** Concentration of force
Another component of the pain a spankee feels when being spanked is
the surface area of where the spanking takes place. Ultimately, the
same amount of work will be done to the buttocks, but it will be
spread out the surface area of the spanking area.

This is why thinner implements are more "stingy" and larger implements
are more "thuddy".

To determine the amount of kinetic energy being exerted per m^2, we
can divide the total force by the surface area to get how many
Netwons of force that will be exerted on that surface area:

\begin{equation}
F = E_k / A
\end{equation}

* Metadata 							   :noexport:
#  LocalWords: LocalWords tex blackbelt acc Kgs TBLNAME
